spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 416592159276-j2claq007vu5g9odhpmort9neraa5cou.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email